"""Emit generated UI key modules (stdlib only)."""

from __future__ import annotations

import hashlib
import json
import keyword
from datetime import datetime, timezone
from pathlib import Path

GENERATOR_VERSION = 4


def class_name_from_root_filename(filename: str) -> str:
    stem = Path(filename).stem
    return "Ui" + "".join(part.capitalize() for part in stem.split("_"))


def module_name_from_root_filename(filename: str) -> str:
    stem = Path(filename).stem
    return stem.replace("_", "")


def _safe_attr(name: str) -> str:
    if not name.isidentifier():
        raise ValueError(f"Widget name is not a valid Python identifier: {name!r}")
    if keyword.iskeyword(name):
        raise ValueError(f"Widget name is a Python keyword: {name!r}")
    return name


def combined_fingerprint_hex(per_root: dict[str, str]) -> str:
    """Deterministic digest for the generated header comment."""
    payload = json.dumps(per_root, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _build_key_module_source(
    *,
    root_filename: str,
    module_name: str,
    names: tuple[str, ...],
    types_by_name: dict[str, str],
    fingerprint: str,
    generated_at: str,
) -> str:
    ui_class_name = "".join(part.capitalize() for part in module_name.split("_")) + "Ui"
    referenced_types = {"QWidget", *types_by_name.values()}
    qt_widget_types = sorted(
        name
        for name in referenced_types
        if name.startswith("Q") and name not in {"Qt", "QStyle"}
    )
    qt_gui_types = sorted(name for name in qt_widget_types if name == "QAction")
    qt_widget_types = [name for name in qt_widget_types if name not in set(qt_gui_types)]
    lines: list[str] = [
        f'"""AUTO-GENERATED by ui_keys (v{GENERATOR_VERSION}) — do not edit.',
        f"    generated_at: {generated_at}",
        f"    module: {module_name}",
        f"    source_xml: {root_filename}",
        f"    fingerprint: {fingerprint}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING, cast",
        "",
        "if TYPE_CHECKING:",
    ]
    if qt_gui_types:
        lines.extend(
            [
                "    from PySide6.QtGui import (",
            ]
        )
        for type_name in qt_gui_types:
            lines.append(f"        {type_name},")
        lines.extend(
            [
                "    )",
            ]
        )
    lines.extend(
        [
        "    from PySide6.QtWidgets import (",
        ]
    )
    for type_name in qt_widget_types:
        lines.append(f"        {type_name},")
    lines.extend(
        [
            "    )",
            "",
            "",
            f"class {ui_class_name}:",
            "    root: QWidget",
        ]
    )
    for name in names:
        attr = _safe_attr(name)
        type_name = types_by_name.get(name, "QWidget")
        lines.append(f"    {attr}: {type_name}")
    lines.extend(
        [
            "",
            "",
            "    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:",
            "        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir",
            "",
            f"        _ui = _load_ui(_xml_root_dir() / {json.dumps(root_filename)}, owner=owner, window=window)",
            "        self.root = _ui.root",
        ]
    )
    for name in names:
        attr = _safe_attr(name)
        lines.append(f"        self.{attr} = _ui.{attr}")
    lines.extend(
        [
            "",
            "",
            f"def bind_ui(ui_obj: object) -> {ui_class_name}:",
            f"    return cast({ui_class_name}, ui_obj)",
            "",
            "",
        ]
    )
    for name in names:
        attr = _safe_attr(name)
        lines.append(f"{attr} = {json.dumps(name)}")
    lines.append("")
    all_names = ", ".join(
        [json.dumps(ui_class_name), json.dumps("bind_ui")]
        + [json.dumps(_safe_attr(name)) for name in names]
    )
    lines.append(f"__all__ = ({all_names},)")
    lines.append("")
    return "\n".join(lines)


def build_module_sources(
    *,
    root_filenames: tuple[str, ...],
    per_root_names: dict[str, tuple[str, ...]],
    per_root_types: dict[str, dict[str, str]],
    per_root_fingerprints: dict[str, str],
    generated_at: str | None = None,
) -> dict[str, str]:
    """Build source for generated package files keyed by relative path."""
    if generated_at is None:
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    _ = combined_fingerprint_hex(per_root_fingerprints)
    sources: dict[str, str] = {}
    for filename in root_filenames:
        names = per_root_names[filename]
        module_name = module_name_from_root_filename(filename)
        sources[f"{module_name}.py"] = _build_key_module_source(
            root_filename=filename,
            module_name=module_name,
            names=names,
            types_by_name=per_root_types[filename],
            fingerprint=per_root_fingerprints[filename],
            generated_at=generated_at,
        )
    return sources
