"""AUTO-GENERATED by ui_keys (v4) — do not edit.
    generated_at: 2026-04-27T16:39:53Z
    module: advancededideditordialog
    source_xml: advanced_edid_editor_dialog.xml
    fingerprint: a394cdbd4378c0eefb5b5349aef0cd2c4e957a47ecc8b1772e407448210e9768
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from PySide6.QtWidgets import (
        QCheckBox,
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QFormLayout,
        QHBoxLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QPushButton,
        QSpinBox,
        QTabWidget,
        QTextEdit,
        QVBoxLayout,
        QWidget,
    )


class AdvancededideditordialogUi:
    root: QWidget
    add_cea_button: QPushButton
    add_cea_extension_button: QPushButton
    add_did_button: QPushButton
    add_timing_button: QPushButton
    advanced_edid_editor_dialog: QDialog
    advanced_layout: QVBoxLayout
    advanced_tabs: QTabWidget
    apply_cea_button: QPushButton
    apply_did_button: QPushButton
    buttons: QDialogButtonBox
    cea_buttons: QHBoxLayout
    cea_form: QFormLayout
    cea_layout: QVBoxLayout
    cea_list: QListWidget
    cea_payload: QTextEdit
    cea_preset: QComboBox
    cea_tab: QWidget
    cea_tag: QSpinBox
    delete_cea_button: QPushButton
    delete_cea_extension_button: QPushButton
    delete_did_button: QPushButton
    delete_timing_button: QPushButton
    detailed_buttons: QHBoxLayout
    detailed_form: QFormLayout
    detailed_layout: QVBoxLayout
    detailed_list: QListWidget
    detailed_tab: QWidget
    did_payload: QTextEdit
    did_preset: QComboBox
    did_revision: QSpinBox
    did_tag: QSpinBox
    displayid_buttons: QHBoxLayout
    displayid_form: QFormLayout
    displayid_layout: QVBoxLayout
    displayid_list: QListWidget
    displayid_tab: QWidget
    down_cea_button: QPushButton
    down_did_button: QPushButton
    established_layout: QVBoxLayout
    established_list: QListWidget
    established_tab: QWidget
    extension_buttons: QHBoxLayout
    extension_combo: QComboBox
    extension_down_button: QPushButton
    extension_up_button: QPushButton
    limits_form: QFormLayout
    limits_tab: QWidget
    load_cea_button: QPushButton
    load_did_button: QPushButton
    mode_controls: QHBoxLayout
    mode_help_label: QLabel
    mode_toggle_button: QPushButton
    preferred_timing_button: QPushButton
    prop_analog_level: QComboBox
    prop_bit_depth: QComboBox
    prop_composite_sync: QCheckBox
    prop_continuous: QCheckBox
    prop_digital: QCheckBox
    prop_gamma: QSpinBox
    prop_height: QSpinBox
    prop_interface: QComboBox
    prop_manufacturer: QLineEdit
    prop_name: QLineEdit
    prop_preferred: QCheckBox
    prop_product: QSpinBox
    prop_revision: QSpinBox
    prop_separate_sync: QCheckBox
    prop_serial_number: QLineEdit
    prop_serial_text: QLineEdit
    prop_srgb: QCheckBox
    prop_sync_on_green: QCheckBox
    prop_text: QLineEdit
    prop_version: QSpinBox
    prop_week: QSpinBox
    prop_width: QSpinBox
    prop_year: QSpinBox
    properties_form: QFormLayout
    properties_tab: QWidget
    range_max_clock: QSpinBox
    range_max_h: QSpinBox
    range_max_v: QSpinBox
    range_min_h: QSpinBox
    range_min_v: QSpinBox
    replace_timing_button: QPushButton
    standard_apply_button: QPushButton
    standard_aspect: QComboBox
    standard_buttons: QHBoxLayout
    standard_clear_button: QPushButton
    standard_defaults_button: QPushButton
    standard_form: QFormLayout
    standard_height: QSpinBox
    standard_layout: QVBoxLayout
    standard_list: QListWidget
    standard_refresh: QSpinBox
    standard_tab: QWidget
    standard_width: QSpinBox
    timing_height: QSpinBox
    timing_mode: QComboBox
    timing_refresh: QSpinBox
    timing_width: QSpinBox
    up_cea_button: QPushButton
    up_did_button: QPushButton


    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:
        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir

        _ui = _load_ui(_xml_root_dir() / "advanced_edid_editor_dialog.xml", owner=owner, window=window)
        self.root = _ui.root
        self.add_cea_button = _ui.add_cea_button
        self.add_cea_extension_button = _ui.add_cea_extension_button
        self.add_did_button = _ui.add_did_button
        self.add_timing_button = _ui.add_timing_button
        self.advanced_edid_editor_dialog = _ui.advanced_edid_editor_dialog
        self.advanced_layout = _ui.advanced_layout
        self.advanced_tabs = _ui.advanced_tabs
        self.apply_cea_button = _ui.apply_cea_button
        self.apply_did_button = _ui.apply_did_button
        self.buttons = _ui.buttons
        self.cea_buttons = _ui.cea_buttons
        self.cea_form = _ui.cea_form
        self.cea_layout = _ui.cea_layout
        self.cea_list = _ui.cea_list
        self.cea_payload = _ui.cea_payload
        self.cea_preset = _ui.cea_preset
        self.cea_tab = _ui.cea_tab
        self.cea_tag = _ui.cea_tag
        self.delete_cea_button = _ui.delete_cea_button
        self.delete_cea_extension_button = _ui.delete_cea_extension_button
        self.delete_did_button = _ui.delete_did_button
        self.delete_timing_button = _ui.delete_timing_button
        self.detailed_buttons = _ui.detailed_buttons
        self.detailed_form = _ui.detailed_form
        self.detailed_layout = _ui.detailed_layout
        self.detailed_list = _ui.detailed_list
        self.detailed_tab = _ui.detailed_tab
        self.did_payload = _ui.did_payload
        self.did_preset = _ui.did_preset
        self.did_revision = _ui.did_revision
        self.did_tag = _ui.did_tag
        self.displayid_buttons = _ui.displayid_buttons
        self.displayid_form = _ui.displayid_form
        self.displayid_layout = _ui.displayid_layout
        self.displayid_list = _ui.displayid_list
        self.displayid_tab = _ui.displayid_tab
        self.down_cea_button = _ui.down_cea_button
        self.down_did_button = _ui.down_did_button
        self.established_layout = _ui.established_layout
        self.established_list = _ui.established_list
        self.established_tab = _ui.established_tab
        self.extension_buttons = _ui.extension_buttons
        self.extension_combo = _ui.extension_combo
        self.extension_down_button = _ui.extension_down_button
        self.extension_up_button = _ui.extension_up_button
        self.limits_form = _ui.limits_form
        self.limits_tab = _ui.limits_tab
        self.load_cea_button = _ui.load_cea_button
        self.load_did_button = _ui.load_did_button
        self.mode_controls = _ui.mode_controls
        self.mode_help_label = _ui.mode_help_label
        self.mode_toggle_button = _ui.mode_toggle_button
        self.preferred_timing_button = _ui.preferred_timing_button
        self.prop_analog_level = _ui.prop_analog_level
        self.prop_bit_depth = _ui.prop_bit_depth
        self.prop_composite_sync = _ui.prop_composite_sync
        self.prop_continuous = _ui.prop_continuous
        self.prop_digital = _ui.prop_digital
        self.prop_gamma = _ui.prop_gamma
        self.prop_height = _ui.prop_height
        self.prop_interface = _ui.prop_interface
        self.prop_manufacturer = _ui.prop_manufacturer
        self.prop_name = _ui.prop_name
        self.prop_preferred = _ui.prop_preferred
        self.prop_product = _ui.prop_product
        self.prop_revision = _ui.prop_revision
        self.prop_separate_sync = _ui.prop_separate_sync
        self.prop_serial_number = _ui.prop_serial_number
        self.prop_serial_text = _ui.prop_serial_text
        self.prop_srgb = _ui.prop_srgb
        self.prop_sync_on_green = _ui.prop_sync_on_green
        self.prop_text = _ui.prop_text
        self.prop_version = _ui.prop_version
        self.prop_week = _ui.prop_week
        self.prop_width = _ui.prop_width
        self.prop_year = _ui.prop_year
        self.properties_form = _ui.properties_form
        self.properties_tab = _ui.properties_tab
        self.range_max_clock = _ui.range_max_clock
        self.range_max_h = _ui.range_max_h
        self.range_max_v = _ui.range_max_v
        self.range_min_h = _ui.range_min_h
        self.range_min_v = _ui.range_min_v
        self.replace_timing_button = _ui.replace_timing_button
        self.standard_apply_button = _ui.standard_apply_button
        self.standard_aspect = _ui.standard_aspect
        self.standard_buttons = _ui.standard_buttons
        self.standard_clear_button = _ui.standard_clear_button
        self.standard_defaults_button = _ui.standard_defaults_button
        self.standard_form = _ui.standard_form
        self.standard_height = _ui.standard_height
        self.standard_layout = _ui.standard_layout
        self.standard_list = _ui.standard_list
        self.standard_refresh = _ui.standard_refresh
        self.standard_tab = _ui.standard_tab
        self.standard_width = _ui.standard_width
        self.timing_height = _ui.timing_height
        self.timing_mode = _ui.timing_mode
        self.timing_refresh = _ui.timing_refresh
        self.timing_width = _ui.timing_width
        self.up_cea_button = _ui.up_cea_button
        self.up_did_button = _ui.up_did_button


def bind_ui(ui_obj: object) -> AdvancededideditordialogUi:
    return cast(AdvancededideditordialogUi, ui_obj)


add_cea_button = "add_cea_button"
add_cea_extension_button = "add_cea_extension_button"
add_did_button = "add_did_button"
add_timing_button = "add_timing_button"
advanced_edid_editor_dialog = "advanced_edid_editor_dialog"
advanced_layout = "advanced_layout"
advanced_tabs = "advanced_tabs"
apply_cea_button = "apply_cea_button"
apply_did_button = "apply_did_button"
buttons = "buttons"
cea_buttons = "cea_buttons"
cea_form = "cea_form"
cea_layout = "cea_layout"
cea_list = "cea_list"
cea_payload = "cea_payload"
cea_preset = "cea_preset"
cea_tab = "cea_tab"
cea_tag = "cea_tag"
delete_cea_button = "delete_cea_button"
delete_cea_extension_button = "delete_cea_extension_button"
delete_did_button = "delete_did_button"
delete_timing_button = "delete_timing_button"
detailed_buttons = "detailed_buttons"
detailed_form = "detailed_form"
detailed_layout = "detailed_layout"
detailed_list = "detailed_list"
detailed_tab = "detailed_tab"
did_payload = "did_payload"
did_preset = "did_preset"
did_revision = "did_revision"
did_tag = "did_tag"
displayid_buttons = "displayid_buttons"
displayid_form = "displayid_form"
displayid_layout = "displayid_layout"
displayid_list = "displayid_list"
displayid_tab = "displayid_tab"
down_cea_button = "down_cea_button"
down_did_button = "down_did_button"
established_layout = "established_layout"
established_list = "established_list"
established_tab = "established_tab"
extension_buttons = "extension_buttons"
extension_combo = "extension_combo"
extension_down_button = "extension_down_button"
extension_up_button = "extension_up_button"
limits_form = "limits_form"
limits_tab = "limits_tab"
load_cea_button = "load_cea_button"
load_did_button = "load_did_button"
mode_controls = "mode_controls"
mode_help_label = "mode_help_label"
mode_toggle_button = "mode_toggle_button"
preferred_timing_button = "preferred_timing_button"
prop_analog_level = "prop_analog_level"
prop_bit_depth = "prop_bit_depth"
prop_composite_sync = "prop_composite_sync"
prop_continuous = "prop_continuous"
prop_digital = "prop_digital"
prop_gamma = "prop_gamma"
prop_height = "prop_height"
prop_interface = "prop_interface"
prop_manufacturer = "prop_manufacturer"
prop_name = "prop_name"
prop_preferred = "prop_preferred"
prop_product = "prop_product"
prop_revision = "prop_revision"
prop_separate_sync = "prop_separate_sync"
prop_serial_number = "prop_serial_number"
prop_serial_text = "prop_serial_text"
prop_srgb = "prop_srgb"
prop_sync_on_green = "prop_sync_on_green"
prop_text = "prop_text"
prop_version = "prop_version"
prop_week = "prop_week"
prop_width = "prop_width"
prop_year = "prop_year"
properties_form = "properties_form"
properties_tab = "properties_tab"
range_max_clock = "range_max_clock"
range_max_h = "range_max_h"
range_max_v = "range_max_v"
range_min_h = "range_min_h"
range_min_v = "range_min_v"
replace_timing_button = "replace_timing_button"
standard_apply_button = "standard_apply_button"
standard_aspect = "standard_aspect"
standard_buttons = "standard_buttons"
standard_clear_button = "standard_clear_button"
standard_defaults_button = "standard_defaults_button"
standard_form = "standard_form"
standard_height = "standard_height"
standard_layout = "standard_layout"
standard_list = "standard_list"
standard_refresh = "standard_refresh"
standard_tab = "standard_tab"
standard_width = "standard_width"
timing_height = "timing_height"
timing_mode = "timing_mode"
timing_refresh = "timing_refresh"
timing_width = "timing_width"
up_cea_button = "up_cea_button"
up_did_button = "up_did_button"

__all__ = ("AdvancededideditordialogUi", "bind_ui", "add_cea_button", "add_cea_extension_button", "add_did_button", "add_timing_button", "advanced_edid_editor_dialog", "advanced_layout", "advanced_tabs", "apply_cea_button", "apply_did_button", "buttons", "cea_buttons", "cea_form", "cea_layout", "cea_list", "cea_payload", "cea_preset", "cea_tab", "cea_tag", "delete_cea_button", "delete_cea_extension_button", "delete_did_button", "delete_timing_button", "detailed_buttons", "detailed_form", "detailed_layout", "detailed_list", "detailed_tab", "did_payload", "did_preset", "did_revision", "did_tag", "displayid_buttons", "displayid_form", "displayid_layout", "displayid_list", "displayid_tab", "down_cea_button", "down_did_button", "established_layout", "established_list", "established_tab", "extension_buttons", "extension_combo", "extension_down_button", "extension_up_button", "limits_form", "limits_tab", "load_cea_button", "load_did_button", "mode_controls", "mode_help_label", "mode_toggle_button", "preferred_timing_button", "prop_analog_level", "prop_bit_depth", "prop_composite_sync", "prop_continuous", "prop_digital", "prop_gamma", "prop_height", "prop_interface", "prop_manufacturer", "prop_name", "prop_preferred", "prop_product", "prop_revision", "prop_separate_sync", "prop_serial_number", "prop_serial_text", "prop_srgb", "prop_sync_on_green", "prop_text", "prop_version", "prop_week", "prop_width", "prop_year", "properties_form", "properties_tab", "range_max_clock", "range_max_h", "range_max_v", "range_min_h", "range_min_v", "replace_timing_button", "standard_apply_button", "standard_aspect", "standard_buttons", "standard_clear_button", "standard_defaults_button", "standard_form", "standard_height", "standard_layout", "standard_list", "standard_refresh", "standard_tab", "standard_width", "timing_height", "timing_mode", "timing_refresh", "timing_width", "up_cea_button", "up_did_button",)
