"""AUTO-GENERATED by ui_keys (v4) — do not edit.
    generated_at: 2026-04-27T16:39:53Z
    module: decodedediddialog
    source_xml: decoded_edid_dialog.xml
    fingerprint: 51cf9d9e51885e35f7ac24841fe92d56e367048ca12706ef222e791828879ddd
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from PySide6.QtWidgets import (
        QCheckBox,
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QFormLayout,
        QLineEdit,
        QPlainTextEdit,
        QSpinBox,
        QTabWidget,
        QVBoxLayout,
        QWidget,
    )


class DecodedediddialogUi:
    root: QWidget
    active_off_check: QCheckBox
    analog_level_combo: QComboBox
    bit_depth_combo: QComboBox
    buttons: QDialogButtonBox
    color_25: QSpinBox
    color_26: QSpinBox
    color_27: QSpinBox
    color_28: QSpinBox
    color_29: QSpinBox
    color_30: QSpinBox
    color_31: QSpinBox
    color_32: QSpinBox
    color_33: QSpinBox
    color_34: QSpinBox
    color_form: QFormLayout
    color_tab: QWidget
    composite_sync_check: QCheckBox
    continuous_check: QCheckBox
    decoded_edid_dialog: QDialog
    decoded_layout: QVBoxLayout
    decoded_text: QPlainTextEdit
    descriptor_form: QFormLayout
    descriptor_tab: QWidget
    digital_check: QCheckBox
    display_form: QFormLayout
    display_tab: QWidget
    edit_tabs: QTabWidget
    gamma_spin: QSpinBox
    height_spin: QSpinBox
    identity_form: QFormLayout
    identity_tab: QWidget
    interface_combo: QComboBox
    manufacturer_edit: QLineEdit
    name_edit: QLineEdit
    preferred_check: QCheckBox
    product_spin: QSpinBox
    range_max_clock: QSpinBox
    range_max_h: QSpinBox
    range_max_v: QSpinBox
    range_min_h: QSpinBox
    range_min_v: QSpinBox
    revision_spin: QSpinBox
    separate_sync_check: QCheckBox
    serial_edit: QLineEdit
    serial_number_edit: QLineEdit
    srgb_check: QCheckBox
    standby_check: QCheckBox
    suspend_check: QCheckBox
    sync_on_green_check: QCheckBox
    text_edit: QLineEdit
    version_spin: QSpinBox
    week_spin: QSpinBox
    width_spin: QSpinBox
    year_spin: QSpinBox


    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:
        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir

        _ui = _load_ui(_xml_root_dir() / "decoded_edid_dialog.xml", owner=owner, window=window)
        self.root = _ui.root
        self.active_off_check = _ui.active_off_check
        self.analog_level_combo = _ui.analog_level_combo
        self.bit_depth_combo = _ui.bit_depth_combo
        self.buttons = _ui.buttons
        self.color_25 = _ui.color_25
        self.color_26 = _ui.color_26
        self.color_27 = _ui.color_27
        self.color_28 = _ui.color_28
        self.color_29 = _ui.color_29
        self.color_30 = _ui.color_30
        self.color_31 = _ui.color_31
        self.color_32 = _ui.color_32
        self.color_33 = _ui.color_33
        self.color_34 = _ui.color_34
        self.color_form = _ui.color_form
        self.color_tab = _ui.color_tab
        self.composite_sync_check = _ui.composite_sync_check
        self.continuous_check = _ui.continuous_check
        self.decoded_edid_dialog = _ui.decoded_edid_dialog
        self.decoded_layout = _ui.decoded_layout
        self.decoded_text = _ui.decoded_text
        self.descriptor_form = _ui.descriptor_form
        self.descriptor_tab = _ui.descriptor_tab
        self.digital_check = _ui.digital_check
        self.display_form = _ui.display_form
        self.display_tab = _ui.display_tab
        self.edit_tabs = _ui.edit_tabs
        self.gamma_spin = _ui.gamma_spin
        self.height_spin = _ui.height_spin
        self.identity_form = _ui.identity_form
        self.identity_tab = _ui.identity_tab
        self.interface_combo = _ui.interface_combo
        self.manufacturer_edit = _ui.manufacturer_edit
        self.name_edit = _ui.name_edit
        self.preferred_check = _ui.preferred_check
        self.product_spin = _ui.product_spin
        self.range_max_clock = _ui.range_max_clock
        self.range_max_h = _ui.range_max_h
        self.range_max_v = _ui.range_max_v
        self.range_min_h = _ui.range_min_h
        self.range_min_v = _ui.range_min_v
        self.revision_spin = _ui.revision_spin
        self.separate_sync_check = _ui.separate_sync_check
        self.serial_edit = _ui.serial_edit
        self.serial_number_edit = _ui.serial_number_edit
        self.srgb_check = _ui.srgb_check
        self.standby_check = _ui.standby_check
        self.suspend_check = _ui.suspend_check
        self.sync_on_green_check = _ui.sync_on_green_check
        self.text_edit = _ui.text_edit
        self.version_spin = _ui.version_spin
        self.week_spin = _ui.week_spin
        self.width_spin = _ui.width_spin
        self.year_spin = _ui.year_spin


def bind_ui(ui_obj: object) -> DecodedediddialogUi:
    return cast(DecodedediddialogUi, ui_obj)


active_off_check = "active_off_check"
analog_level_combo = "analog_level_combo"
bit_depth_combo = "bit_depth_combo"
buttons = "buttons"
color_25 = "color_25"
color_26 = "color_26"
color_27 = "color_27"
color_28 = "color_28"
color_29 = "color_29"
color_30 = "color_30"
color_31 = "color_31"
color_32 = "color_32"
color_33 = "color_33"
color_34 = "color_34"
color_form = "color_form"
color_tab = "color_tab"
composite_sync_check = "composite_sync_check"
continuous_check = "continuous_check"
decoded_edid_dialog = "decoded_edid_dialog"
decoded_layout = "decoded_layout"
decoded_text = "decoded_text"
descriptor_form = "descriptor_form"
descriptor_tab = "descriptor_tab"
digital_check = "digital_check"
display_form = "display_form"
display_tab = "display_tab"
edit_tabs = "edit_tabs"
gamma_spin = "gamma_spin"
height_spin = "height_spin"
identity_form = "identity_form"
identity_tab = "identity_tab"
interface_combo = "interface_combo"
manufacturer_edit = "manufacturer_edit"
name_edit = "name_edit"
preferred_check = "preferred_check"
product_spin = "product_spin"
range_max_clock = "range_max_clock"
range_max_h = "range_max_h"
range_max_v = "range_max_v"
range_min_h = "range_min_h"
range_min_v = "range_min_v"
revision_spin = "revision_spin"
separate_sync_check = "separate_sync_check"
serial_edit = "serial_edit"
serial_number_edit = "serial_number_edit"
srgb_check = "srgb_check"
standby_check = "standby_check"
suspend_check = "suspend_check"
sync_on_green_check = "sync_on_green_check"
text_edit = "text_edit"
version_spin = "version_spin"
week_spin = "week_spin"
width_spin = "width_spin"
year_spin = "year_spin"

__all__ = ("DecodedediddialogUi", "bind_ui", "active_off_check", "analog_level_combo", "bit_depth_combo", "buttons", "color_25", "color_26", "color_27", "color_28", "color_29", "color_30", "color_31", "color_32", "color_33", "color_34", "color_form", "color_tab", "composite_sync_check", "continuous_check", "decoded_edid_dialog", "decoded_layout", "decoded_text", "descriptor_form", "descriptor_tab", "digital_check", "display_form", "display_tab", "edit_tabs", "gamma_spin", "height_spin", "identity_form", "identity_tab", "interface_combo", "manufacturer_edit", "name_edit", "preferred_check", "product_spin", "range_max_clock", "range_max_h", "range_max_v", "range_min_h", "range_min_v", "revision_spin", "separate_sync_check", "serial_edit", "serial_number_edit", "srgb_check", "standby_check", "suspend_check", "sync_on_green_check", "text_edit", "version_spin", "week_spin", "width_spin", "year_spin",)
