"""AUTO-GENERATED by ui_keys (v4) — do not edit.
    generated_at: 2026-04-27T16:39:53Z
    module: edidcreationwizard
    source_xml: edid_creation_wizard.xml
    fingerprint: c08e5f955d63d9b0a1f52e5d79d26dbe6b16787a7da71f0b68042ade9a93cf44
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from PySide6.QtWidgets import (
        QCheckBox,
        QComboBox,
        QGridLayout,
        QLabel,
        QLineEdit,
        QSpinBox,
        QTextEdit,
        QVBoxLayout,
        QWidget,
        QWizard,
        QWizardPage,
    )


class EdidcreationwizardUi:
    root: QWidget
    advanced_hint: QLabel
    advanced_layout: QVBoxLayout
    advanced_page: QWizardPage
    edid_creation_wizard: QWizard
    help_layout: QVBoxLayout
    help_page: QWizardPage
    identity_grid: QGridLayout
    identity_outer: QVBoxLayout
    identity_page: QWizardPage
    intro: QLabel
    native_grid: QGridLayout
    native_page: QWizardPage
    wizard_h_active: QSpinBox
    wizard_height_cm: QSpinBox
    wizard_help: QTextEdit
    wizard_manufacturer: QLineEdit
    wizard_name: QLineEdit
    wizard_open_advanced: QCheckBox
    wizard_product: QSpinBox
    wizard_refresh: QSpinBox
    wizard_serial: QSpinBox
    wizard_timing_mode: QComboBox
    wizard_v_active: QSpinBox
    wizard_width_cm: QSpinBox


    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:
        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir

        _ui = _load_ui(_xml_root_dir() / "edid_creation_wizard.xml", owner=owner, window=window)
        self.root = _ui.root
        self.advanced_hint = _ui.advanced_hint
        self.advanced_layout = _ui.advanced_layout
        self.advanced_page = _ui.advanced_page
        self.edid_creation_wizard = _ui.edid_creation_wizard
        self.help_layout = _ui.help_layout
        self.help_page = _ui.help_page
        self.identity_grid = _ui.identity_grid
        self.identity_outer = _ui.identity_outer
        self.identity_page = _ui.identity_page
        self.intro = _ui.intro
        self.native_grid = _ui.native_grid
        self.native_page = _ui.native_page
        self.wizard_h_active = _ui.wizard_h_active
        self.wizard_height_cm = _ui.wizard_height_cm
        self.wizard_help = _ui.wizard_help
        self.wizard_manufacturer = _ui.wizard_manufacturer
        self.wizard_name = _ui.wizard_name
        self.wizard_open_advanced = _ui.wizard_open_advanced
        self.wizard_product = _ui.wizard_product
        self.wizard_refresh = _ui.wizard_refresh
        self.wizard_serial = _ui.wizard_serial
        self.wizard_timing_mode = _ui.wizard_timing_mode
        self.wizard_v_active = _ui.wizard_v_active
        self.wizard_width_cm = _ui.wizard_width_cm


def bind_ui(ui_obj: object) -> EdidcreationwizardUi:
    return cast(EdidcreationwizardUi, ui_obj)


advanced_hint = "advanced_hint"
advanced_layout = "advanced_layout"
advanced_page = "advanced_page"
edid_creation_wizard = "edid_creation_wizard"
help_layout = "help_layout"
help_page = "help_page"
identity_grid = "identity_grid"
identity_outer = "identity_outer"
identity_page = "identity_page"
intro = "intro"
native_grid = "native_grid"
native_page = "native_page"
wizard_h_active = "wizard_h_active"
wizard_height_cm = "wizard_height_cm"
wizard_help = "wizard_help"
wizard_manufacturer = "wizard_manufacturer"
wizard_name = "wizard_name"
wizard_open_advanced = "wizard_open_advanced"
wizard_product = "wizard_product"
wizard_refresh = "wizard_refresh"
wizard_serial = "wizard_serial"
wizard_timing_mode = "wizard_timing_mode"
wizard_v_active = "wizard_v_active"
wizard_width_cm = "wizard_width_cm"

__all__ = ("EdidcreationwizardUi", "bind_ui", "advanced_hint", "advanced_layout", "advanced_page", "edid_creation_wizard", "help_layout", "help_page", "identity_grid", "identity_outer", "identity_page", "intro", "native_grid", "native_page", "wizard_h_active", "wizard_height_cm", "wizard_help", "wizard_manufacturer", "wizard_name", "wizard_open_advanced", "wizard_product", "wizard_refresh", "wizard_serial", "wizard_timing_mode", "wizard_v_active", "wizard_width_cm",)
