"""AUTO-GENERATED by ui_keys (v4) — do not edit.
    generated_at: 2026-04-27T16:39:53Z
    module: monitormanagersection
    source_xml: monitor_manager_section.xml
    fingerprint: 9f91f8b4405a0fdb889ef8f2530740fdbb5c391c9fc21d4adc471f2143dd5300
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from PySide6.QtWidgets import (
        QComboBox,
        QGroupBox,
        QHBoxLayout,
        QLabel,
        QListWidget,
        QPushButton,
        QVBoxLayout,
        QWidget,
    )


class MonitormanagersectionUi:
    root: QWidget
    detailed_buttons: QHBoxLayout
    detailed_group: QGroupBox
    detailed_layout: QVBoxLayout
    established_group: QGroupBox
    established_layout: QVBoxLayout
    extension_buttons: QHBoxLayout
    extension_group: QGroupBox
    extension_layout: QVBoxLayout
    manager_add_detailed_button: QPushButton
    manager_add_extension_button: QPushButton
    manager_add_standard_button: QPushButton
    manager_body: QHBoxLayout
    manager_copy_button: QPushButton
    manager_delete_all_detailed_button: QPushButton
    manager_delete_all_extension_button: QPushButton
    manager_delete_all_standard_button: QPushButton
    manager_delete_button: QPushButton
    manager_delete_detailed_button: QPushButton
    manager_delete_extension_button: QPushButton
    manager_delete_monitor_button: QPushButton
    manager_delete_standard_button: QPushButton
    manager_detailed_list: QListWidget
    manager_edit_button: QPushButton
    manager_edit_detailed_button: QPushButton
    manager_edit_extension_button: QPushButton
    manager_edit_standard_button: QPushButton
    manager_established_list: QListWidget
    manager_extension_list: QListWidget
    manager_group: QGroupBox
    manager_intro: QLabel
    manager_layout: QVBoxLayout
    manager_lists_layout: QVBoxLayout
    manager_lists_panel: QWidget
    manager_paste_button: QPushButton
    manager_refresh_button: QPushButton
    manager_selected_combo: QComboBox
    manager_standard_list: QListWidget
    manager_summary_label: QLabel
    manager_toolbar: QHBoxLayout
    standard_buttons: QHBoxLayout
    standard_group: QGroupBox
    standard_layout: QVBoxLayout


    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:
        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir

        _ui = _load_ui(_xml_root_dir() / "monitor_manager_section.xml", owner=owner, window=window)
        self.root = _ui.root
        self.detailed_buttons = _ui.detailed_buttons
        self.detailed_group = _ui.detailed_group
        self.detailed_layout = _ui.detailed_layout
        self.established_group = _ui.established_group
        self.established_layout = _ui.established_layout
        self.extension_buttons = _ui.extension_buttons
        self.extension_group = _ui.extension_group
        self.extension_layout = _ui.extension_layout
        self.manager_add_detailed_button = _ui.manager_add_detailed_button
        self.manager_add_extension_button = _ui.manager_add_extension_button
        self.manager_add_standard_button = _ui.manager_add_standard_button
        self.manager_body = _ui.manager_body
        self.manager_copy_button = _ui.manager_copy_button
        self.manager_delete_all_detailed_button = _ui.manager_delete_all_detailed_button
        self.manager_delete_all_extension_button = _ui.manager_delete_all_extension_button
        self.manager_delete_all_standard_button = _ui.manager_delete_all_standard_button
        self.manager_delete_button = _ui.manager_delete_button
        self.manager_delete_detailed_button = _ui.manager_delete_detailed_button
        self.manager_delete_extension_button = _ui.manager_delete_extension_button
        self.manager_delete_monitor_button = _ui.manager_delete_monitor_button
        self.manager_delete_standard_button = _ui.manager_delete_standard_button
        self.manager_detailed_list = _ui.manager_detailed_list
        self.manager_edit_button = _ui.manager_edit_button
        self.manager_edit_detailed_button = _ui.manager_edit_detailed_button
        self.manager_edit_extension_button = _ui.manager_edit_extension_button
        self.manager_edit_standard_button = _ui.manager_edit_standard_button
        self.manager_established_list = _ui.manager_established_list
        self.manager_extension_list = _ui.manager_extension_list
        self.manager_group = _ui.manager_group
        self.manager_intro = _ui.manager_intro
        self.manager_layout = _ui.manager_layout
        self.manager_lists_layout = _ui.manager_lists_layout
        self.manager_lists_panel = _ui.manager_lists_panel
        self.manager_paste_button = _ui.manager_paste_button
        self.manager_refresh_button = _ui.manager_refresh_button
        self.manager_selected_combo = _ui.manager_selected_combo
        self.manager_standard_list = _ui.manager_standard_list
        self.manager_summary_label = _ui.manager_summary_label
        self.manager_toolbar = _ui.manager_toolbar
        self.standard_buttons = _ui.standard_buttons
        self.standard_group = _ui.standard_group
        self.standard_layout = _ui.standard_layout


def bind_ui(ui_obj: object) -> MonitormanagersectionUi:
    return cast(MonitormanagersectionUi, ui_obj)


detailed_buttons = "detailed_buttons"
detailed_group = "detailed_group"
detailed_layout = "detailed_layout"
established_group = "established_group"
established_layout = "established_layout"
extension_buttons = "extension_buttons"
extension_group = "extension_group"
extension_layout = "extension_layout"
manager_add_detailed_button = "manager_add_detailed_button"
manager_add_extension_button = "manager_add_extension_button"
manager_add_standard_button = "manager_add_standard_button"
manager_body = "manager_body"
manager_copy_button = "manager_copy_button"
manager_delete_all_detailed_button = "manager_delete_all_detailed_button"
manager_delete_all_extension_button = "manager_delete_all_extension_button"
manager_delete_all_standard_button = "manager_delete_all_standard_button"
manager_delete_button = "manager_delete_button"
manager_delete_detailed_button = "manager_delete_detailed_button"
manager_delete_extension_button = "manager_delete_extension_button"
manager_delete_monitor_button = "manager_delete_monitor_button"
manager_delete_standard_button = "manager_delete_standard_button"
manager_detailed_list = "manager_detailed_list"
manager_edit_button = "manager_edit_button"
manager_edit_detailed_button = "manager_edit_detailed_button"
manager_edit_extension_button = "manager_edit_extension_button"
manager_edit_standard_button = "manager_edit_standard_button"
manager_established_list = "manager_established_list"
manager_extension_list = "manager_extension_list"
manager_group = "manager_group"
manager_intro = "manager_intro"
manager_layout = "manager_layout"
manager_lists_layout = "manager_lists_layout"
manager_lists_panel = "manager_lists_panel"
manager_paste_button = "manager_paste_button"
manager_refresh_button = "manager_refresh_button"
manager_selected_combo = "manager_selected_combo"
manager_standard_list = "manager_standard_list"
manager_summary_label = "manager_summary_label"
manager_toolbar = "manager_toolbar"
standard_buttons = "standard_buttons"
standard_group = "standard_group"
standard_layout = "standard_layout"

__all__ = ("MonitormanagersectionUi", "bind_ui", "detailed_buttons", "detailed_group", "detailed_layout", "established_group", "established_layout", "extension_buttons", "extension_group", "extension_layout", "manager_add_detailed_button", "manager_add_extension_button", "manager_add_standard_button", "manager_body", "manager_copy_button", "manager_delete_all_detailed_button", "manager_delete_all_extension_button", "manager_delete_all_standard_button", "manager_delete_button", "manager_delete_detailed_button", "manager_delete_extension_button", "manager_delete_monitor_button", "manager_delete_standard_button", "manager_detailed_list", "manager_edit_button", "manager_edit_detailed_button", "manager_edit_extension_button", "manager_edit_standard_button", "manager_established_list", "manager_extension_list", "manager_group", "manager_intro", "manager_layout", "manager_lists_layout", "manager_lists_panel", "manager_paste_button", "manager_refresh_button", "manager_selected_combo", "manager_standard_list", "manager_summary_label", "manager_toolbar", "standard_buttons", "standard_group", "standard_layout",)
