"""AUTO-GENERATED by ui_keys (v4) — do not edit.
    generated_at: 2026-04-27T16:39:53Z
    module: rawblockeditordialog
    source_xml: raw_block_editor_dialog.xml
    fingerprint: 78f9918a75f3e2ddd1d1d29158a18f89e8b86de67e615d50d3dc259e0bc2320d
"""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from PySide6.QtWidgets import (
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QHBoxLayout,
        QPushButton,
        QTextEdit,
        QVBoxLayout,
        QWidget,
    )


class RawblockeditordialogUi:
    root: QWidget
    add_button: QPushButton
    block_combo: QComboBox
    buttons: QDialogButtonBox
    delete_button: QPushButton
    hex_editor: QTextEdit
    raw_block_editor_dialog: QDialog
    raw_block_editor_layout: QVBoxLayout
    raw_block_top: QHBoxLayout


    def __init__(self, *, owner: object | None = None, window: object | None = None) -> None:
        from edid.ui_factory import load_ui as _load_ui, xml_root_dir as _xml_root_dir

        _ui = _load_ui(_xml_root_dir() / "raw_block_editor_dialog.xml", owner=owner, window=window)
        self.root = _ui.root
        self.add_button = _ui.add_button
        self.block_combo = _ui.block_combo
        self.buttons = _ui.buttons
        self.delete_button = _ui.delete_button
        self.hex_editor = _ui.hex_editor
        self.raw_block_editor_dialog = _ui.raw_block_editor_dialog
        self.raw_block_editor_layout = _ui.raw_block_editor_layout
        self.raw_block_top = _ui.raw_block_top


def bind_ui(ui_obj: object) -> RawblockeditordialogUi:
    return cast(RawblockeditordialogUi, ui_obj)


add_button = "add_button"
block_combo = "block_combo"
buttons = "buttons"
delete_button = "delete_button"
hex_editor = "hex_editor"
raw_block_editor_dialog = "raw_block_editor_dialog"
raw_block_editor_layout = "raw_block_editor_layout"
raw_block_top = "raw_block_top"

__all__ = ("RawblockeditordialogUi", "bind_ui", "add_button", "block_combo", "buttons", "delete_button", "hex_editor", "raw_block_editor_dialog", "raw_block_editor_layout", "raw_block_top",)
